### ISSUE TITLE
Resource acquisition is unsound on 0.8 and may leak

### ISSUE THREAD

**Issue by djspiewak** [RichRelevance/scalaz-netty#31]
As an example, see: https://github.com/RichRelevance/scalaz-netty/blob/master/src/main/scala/scalaz/netty/Netty.scala#L34  The `await`+`onComplete` pattern is no longer a sound method for effectfully acquiring and freeing resources in scalaz-stream 0.8.  Instead, you should be using `Process.bracket`.

The reason for this is the fact that preemption semantics are unsound in 0.7 and had to be somewhat altered in 0.8.  In 0.8, preemption is a first-class concept in the algebra, which allows the concurrency machinery to be dramatically simpler and also eliminates several fundamental bugs (notably where finalizers would be entirely missed).

With the code as it is currently written, any preemption of the `server` or `client` processes during resource acquisition (i.e. when the Netty context is initializing) will result in a resource leak and the server will never be shut down.

**Comment by scottcarey** [comment]
To be clear:

The pattern here can leak if the process fails `Process await( <HERE> ) { ... onComplete ... }` but is safe if it fails elsewhere?

**Comment by djspiewak** [comment]
@scottcarey It's not actually when the process fails.  If the process fails (with an error), then everything will be cleaned up in both 0.8 and 0.7.x.  It's when the process is _interrupted_.  For example:

``` scala
import Process._
case object Derp extends RuntimeException

val t: Task[A] = Task delay { Thread.sleep(2000); 42 }    // hang out for a while
def cleanup(i: Int): Task[Unit] = Task delay { println("ran!") }

fail(Derp) merge (await(t) { i => emit(i) onComplete eval_(cleanup(i)) })
```

In 0.7.x, this should print `ran!` to standard out.  In 0.8, it will not.  The way to fix it is the following:

``` scala
fail(Derp) merge bracket(t)(cleanup) { i => emit(i) }
```
